#!/usr/bin/env bash
# script that configures a nez ubuntu machine

apt-get update
apt-get install -y nginx
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
ufw allow 'Nginx HTTP'
new="https://www.youtube.com/watch?v=QH2-TGUlwu4"
sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new permanent;" /etc/nginx/sites-available/default
service nginx restart
