#!/usr/bin/env bash
# This script configures an Ubuntu server

cp /etc/hosts ~/hosts.new
sed -i s/^127.*localhost$/127.0.0.2\ localhost/ ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
